/**
 * Token emitter — converts a resolved ArtDirection into a CSS `:root{…}` block
 * containing ALL design-system custom properties (spec §2).
 *
 * artDirectionToCss(ad) is the single public export. It is called by BaseLayout
 * and injected as an inline <style> so every var() in global.css and components
 * resolves to per-site values. config.tokens overrides are applied last.
 */

import type { ArtDirection } from './art-direction';
import { TYPE_SCALES, computeVerticalScale } from './fonts';

/** Step count above and below 0 in the modular scale. */
const STEPS_ABOVE = 6; // --step-1 … --step-6
const STEPS_BELOW = 1; // --step--1

/**
 * Build one fluid clamp() value for a modular scale step.
 *
 * Formula: clamp(minRem, preferredVw, maxRem)
 *   - minRem  = base * ratio^step  (at min viewport, in rem)
 *   - maxRem  = minRem * 1.35      (gentle fluid ceiling)
 *   - vwExpr  = midpoint in viewport-relative units
 *
 * For step 0 we use the typeScale's explicit base values for fidelity.
 */
function stepClamp(
  step: number,
  baseMinRem: number,
  baseVw: number,
  baseMaxRem: number,
  ratio: number,
): string {
  if (step === 0) {
    return `clamp(${baseMinRem}rem, ${baseVw}vw + ${baseMinRem * 0.5}rem, ${baseMaxRem}rem)`;
  }
  const factor = Math.pow(ratio, step);
  const minRem = +(baseMinRem * factor).toFixed(4);
  const maxRem = +(baseMaxRem * factor).toFixed(4);
  // vw that hits mid-scale at 1200px viewport
  const midRem = (minRem + maxRem) / 2;
  const vw = +((midRem / 12) * 100).toFixed(4);
  return `clamp(${minRem}rem, ${vw}vw + ${(minRem * 0.3).toFixed(4)}rem, ${maxRem}rem)`;
}

/**
 * Shape-family → concrete token values (spec §5.1).
 */
interface ShapeTokens {
  radius: string;
  radiusLg: string;
  radiusPill: string;
  borderWeight: string;
  shadowSm: string;
  shadowMd: string;
  shadowLg: string;
  frameStyle: string;
}

const SHAPE_TOKENS: Record<string, ShapeTokens> = {
  soft: {
    radius: '14px',
    radiusLg: '24px',
    radiusPill: '999px',
    borderWeight: '1px',
    // Open Props layered shadows — far more refined than flat hand-rolled ones.
    shadowSm: 'var(--shadow-2)',
    shadowMd: 'var(--shadow-3)',
    shadowLg: 'var(--shadow-5)',
    frameStyle: 'soft',
  },
  sharp: {
    radius: '0px',
    radiusLg: '0px',
    radiusPill: '0px',
    borderWeight: '2px',
    shadowSm: 'none',
    shadowMd: '3px 3px 0 rgba(0,0,0,.15)',
    shadowLg: '6px 6px 0 rgba(0,0,0,.18)',
    frameStyle: 'sharp',
  },
  editorial: {
    radius: '2px',
    radiusLg: '2px',
    radiusPill: '999px',
    borderWeight: '1px',
    shadowSm: 'none',
    shadowMd: 'none',
    shadowLg: 'none',
    frameStyle: 'editorial',
  },
  'rounded-pill': {
    radius: '18px',
    radiusLg: '18px',
    radiusPill: '999px',
    borderWeight: '1px',
    shadowSm: 'var(--shadow-2)',
    shadowMd: 'var(--shadow-4)',
    shadowLg: 'var(--shadow-6)',
    frameStyle: 'pill',
  },
  framed: {
    radius: '4px',
    radiusLg: '4px',
    radiusPill: '999px',
    borderWeight: '2px',
    shadowSm: '2px 2px 0 rgba(0,0,0,.12)',
    shadowMd: '4px 4px 0 rgba(0,0,0,.16)',
    shadowLg: '8px 8px 0 rgba(0,0,0,.18)',
    frameStyle: 'framed',
  },
};

/**
 * Density → concrete spacing tokens (spec §5.3).
 */
interface DensityTokens {
  sectionPad: string;
  gutter: string;
  maxw: string;
  gridGap: string;
}

const DENSITY_TOKENS: Record<string, DensityTokens> = {
  compact: {
    sectionPad: 'clamp(2.5rem, 6vw, 4rem)',
    gutter: 'clamp(1rem, 3vw, 1.75rem)',
    maxw: '1080px',
    gridGap: 'clamp(1rem, 2vw, 1.5rem)',
  },
  standard: {
    sectionPad: 'clamp(3.5rem, 8vw, 6rem)',
    gutter: 'clamp(1.25rem, 4vw, 2.25rem)',
    maxw: '1140px',
    gridGap: 'clamp(1.25rem, 2.5vw, 2rem)',
  },
  spacious: {
    sectionPad: 'clamp(5rem, 11vw, 9rem)',
    gutter: 'clamp(1.5rem, 5vw, 3rem)',
    maxw: '1200px',
    gridGap: 'clamp(1.5rem, 3vw, 2.5rem)',
  },
};

/**
 * Motion level → concrete duration/distance tokens (spec §5.2).
 * All zeroed when motion === 'none'.
 */
interface MotionTokens {
  motionFade: string;
  motionRise: string;
  motionEase: string;
}

const MOTION_TOKENS: Record<string, MotionTokens> = {
  none: {
    motionFade: '0ms',
    motionRise: '0px',
    motionEase: 'linear',
  },
  subtle: {
    motionFade: '190ms',
    motionRise: '10px',
    motionEase: 'var(--ease-out-3)',
  },
  expressive: {
    motionFade: '320ms',
    motionRise: '20px',
    motionEase: 'var(--ease-spring-3)',
  },
};

/**
 * Convert a resolved ArtDirection into a CSS `:root { … }` string containing
 * all §2.1 tokens. Applies config.tokens overrides last.
 */
export function artDirectionToCss(ad: ArtDirection): string {
  const { palette, fontPairing, typeScale, verticalScale, shape, motion, density, tokenOverrides } =
    ad;

  // ── modular type scale (per-vertical, utopia-core) ─────────────────────────
  // The --step-* ladder is now generated by utopia-core from the resolved
  // VERTICAL scale, so a dentist and a tow company get a different fluid type
  // rhythm (ratio + endpoints), not just different colors. We keep the EXACT
  // same token names + range (--step--1 … --step-6) so every existing var()
  // consumer keeps working unchanged. The hand-rolled stepClamp() below stays as
  // a per-step fallback: if utopia ever omits a step, the ladder never gets a
  // hole. The vertical scale is WCAG-self-healed in fonts.ts (no shrink hazard).
  const computed = computeVerticalScale(verticalScale);
  const { ratio, baseMinRem, baseVw, baseMaxRem } = typeScale;
  const steps: Record<string, string> = {};
  // Below zero: step--1
  for (let i = 1; i <= STEPS_BELOW; i++) {
    steps[`--step--${i}`] =
      computed.typeSteps[-i] ?? stepClamp(-i, baseMinRem, baseVw, baseMaxRem, ratio);
  }
  // Step 0
  steps['--step-0'] = computed.typeSteps[0] ?? stepClamp(0, baseMinRem, baseVw, baseMaxRem, ratio);
  // Above zero
  for (let i = 1; i <= STEPS_ABOVE; i++) {
    steps[`--step-${i}`] =
      computed.typeSteps[i] ?? stepClamp(i, baseMinRem, baseVw, baseMaxRem, ratio);
  }

  // ── fluid space ladder (per-vertical, utopia-core) ─────────────────────────
  // ADDITIVE: a t-shirt-labelled --space-* ramp (--space-2xs … --space-3xl)
  // whose base unit + growth also varies by vertical, giving each category a
  // distinct spacing cadence. These are NEW tokens layered alongside the
  // existing --section-pad / --gutter / --grid-gap (which stay as-is for
  // back-compat); components may opt into --space-* over time. utopia emits
  // px-anchored rem clamps; we pass them through verbatim.
  const spaceSteps: Record<string, string> = {};
  for (const [label, clampStr] of Object.entries(computed.spaceSizes)) {
    spaceSteps[`--space-${label}`] = clampStr;
  }

  // ── shape ────────────────────────────────────────────────────────────────
  const shapeT = SHAPE_TOKENS[shape] ?? SHAPE_TOKENS.soft;

  // ── density ──────────────────────────────────────────────────────────────
  const densityT = DENSITY_TOKENS[density] ?? DENSITY_TOKENS.standard;

  // ── motion ───────────────────────────────────────────────────────────────
  const motionT = MOTION_TOKENS[motion] ?? MOTION_TOKENS.subtle;

  // ── archetype rhythm ──────────────────────────────────────────────────────
  // Each archetype gets a distinct vertical RHYTHM so the page bones differ, not
  // just the hero. These tokens are consumed by archetypes.css. We emit them for
  // every archetype but only classic/magazine read --arch-section-pad here —
  // editorial/utility already set their own .section padding in arch-*.css, so we
  // leave those untouched to avoid a cascade clash. The divider/heading-accent
  // tokens style the section seams + heading rules that give classic & magazine a
  // signature spine.
  const ARCHETYPE_TOKENS: Record<string, { sectionPadMul: string; dividerGap: string }> = {
    // Classic — balanced, calm rhythm; baseline padding, gentle seams.
    classic:   { sectionPadMul: '1',    dividerGap: 'clamp(0.75rem, 2vw, 1.5rem)' },
    // Magazine — punchy, overlapping rhythm: tighter band padding + a bolder seam
    // so dense visual bands stack with editorial cadence.
    magazine:  { sectionPadMul: '0.85', dividerGap: 'clamp(1.25rem, 3vw, 2.5rem)' },
    // editorial/utility carry their own padding in arch-*.css — mirror sensible
    // values here only so the tokens always resolve (CSS for them ignores the mul).
    editorial: { sectionPadMul: '1.35', dividerGap: 'clamp(1.5rem, 4vw, 3rem)' },
    utility:   { sectionPadMul: '0.72', dividerGap: 'clamp(0.5rem, 1.5vw, 1rem)' },
  };
  const archT = ARCHETYPE_TOKENS[ad.archetype] ?? ARCHETYPE_TOKENS.classic;

  // ── pattern opacity — seeded subtle decoration ────────────────────────────
  // Framed/editorial shapes get a bit more pattern; others minimal.
  const patternOpacity =
    shape === 'framed' ? '0.04' : shape === 'editorial' ? '0.03' : '0.02';

  // ── assemble all props ────────────────────────────────────────────────────
  const props: Record<string, string> = {
    // color
    '--brand': palette.brand,
    '--brand-vivid': palette.brandVivid,
    '--brand-vivid-contrast': palette.brandVividContrast,
    '--brand-dark': palette.brandDark,
    '--brand-contrast': palette.brandContrast,
    '--accent': palette.accent,
    '--accent-contrast': palette.accentContrast,
    '--bg': palette.bg,
    '--bg-alt': palette.bgAlt,
    '--bg-deep': palette.bgDeep,
    '--surface': palette.surface,
    '--surface-2': palette.surface2,
    // Derived surface tokens — consistent tint ladder, no per-component ad-hoc color-mix
    '--surface-3': `color-mix(in srgb, var(--surface-2) 60%, var(--bg-alt))`,
    '--brand-tint': `color-mix(in srgb, var(--brand) 10%, var(--surface))`,
    '--text': palette.text,
    '--text-muted': palette.textMuted,
    '--text-on-dark': palette.textOnDark,
    '--border': palette.border,
    '--ring': palette.ring,

    // fonts
    '--font-display': fontPairing.display,
    '--font-body': fontPairing.body,
    '--fw-display': String(typeScale.fwDisplay),
    '--fw-body': String(typeScale.fwBody),
    '--fw-bold': String(typeScale.fwBold),
    '--tracking-display': typeScale.trackingDisplay,
    '--tracking-eyebrow': typeScale.trackingEyebrow,
    '--leading-display': String(typeScale.leadingDisplay),
    '--leading-body': String(typeScale.leadingBody),

    // type scale steps (per-vertical, utopia-core)
    ...steps,

    // fluid space ladder (per-vertical, utopia-core; additive to density tokens)
    ...spaceSteps,

    // shape
    '--radius': shapeT.radius,
    '--radius-lg': shapeT.radiusLg,
    '--radius-pill': shapeT.radiusPill,
    '--border-weight': shapeT.borderWeight,
    '--shadow-sm': shapeT.shadowSm,
    '--shadow-md': shapeT.shadowMd,
    '--shadow-lg': shapeT.shadowLg,
    '--frame-style': shapeT.frameStyle,

    // density
    '--section-pad': densityT.sectionPad,
    '--gutter': densityT.gutter,
    '--maxw': densityT.maxw,
    '--grid-gap': densityT.gridGap,

    // motion
    '--motion-fade': motionT.motionFade,
    '--motion-rise': motionT.motionRise,
    '--motion-ease': motionT.motionEase,

    // archetype rhythm (consumed by archetypes.css for classic/magazine)
    '--arch-section-pad': `calc(var(--section-pad) * ${archT.sectionPadMul})`,
    '--arch-divider-gap': archT.dividerGap,

    // decoration
    '--pattern-opacity': patternOpacity,

    // grain/noise texture
    '--noise-opacity': '0.04',
    '--noise-url': `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E%3Crect width='200' height='200' filter='url(%23n)'/%3E%3C/svg%3E")`,
  };

  // ── apply explicit token overrides (escape hatch) ─────────────────────────
  if (tokenOverrides) {
    for (const [k, v] of Object.entries(tokenOverrides)) {
      if (v !== undefined) {
        // Ensure the key has the -- prefix
        props[k.startsWith('--') ? k : `--${k}`] = v;
      }
    }
  }

  // ── render ────────────────────────────────────────────────────────────────
  const body = Object.entries(props)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

  return `:root {\n${body}\n}`;
}
