/**
 * Site configuration for Dry Creek Estate Winery.
 * Generated by scripts/generate-winery-site.mjs — edit freely.
 *
 * All pages pull their content from this single source of truth.
 * Brand colors, wines, story, contact, and more — all here.
 */

export interface Wine {
  name: string;
  varietal: string;
  type: 'Red' | 'White' | 'Rosé' | 'Blend' | 'Sparkling' | 'Dessert';
  image: string;
  notes: string;
}

export interface BusinessHours {
  day: string;
  hours: string;
}

export const config = {
  name: 'Dry Creek Estate Winery',
  tagline: 'Old-vine Zinfandel rooted in Sonoma tradition',
  seoDescription: 'Dry Creek Estate Winery crafts bold, small-batch Zinfandel and Cabernet Sauvignon from century-old vines in Healdsburg, Sonoma County.',
  area: 'Healdsburg, CA',
  established: 'Est. 1974',

  contact: {
    phone: '(707) 433-2891',
    email: 'info@drycreekestate.com',
    address: '4580 Dry Creek Rd, Healdsburg, CA 95448',
    note: 'We welcome visitors by appointment — call ahead and we\'ll have a glass waiting.',
  },

  social: {
    facebook: 'https://facebook.com/drycreekestate',
    instagram: 'https://instagram.com/drycreekestatewinery',
    yelp: '',
  },

  /** Primary navigation links — shared across every page. */
  nav: [
    { label: 'Home', href: '/' },
    { label: 'Our Wines', href: '/wines/' },
    { label: 'Our Story', href: '/story/' },
    { label: 'Visit', href: '/visit/' },
  ],

  hero: {
    kicker: 'Healdsburg · Dry Creek Valley AVA',
    heading: 'Old-vine Zinfandel from the heart of Sonoma',
    subheading: 'Three generations farming the same rocky benchland since 1974 — where the vines run deep and the wine runs honest.',
    ctaText: 'Explore our wines',
    ctaHref: '/wines/',
  },

  story: {
    heading: 'Three generations, one valley',
    paragraphs: [
      'In 1974, Frank and Loretta Marchetti planted the first Zinfandel canes in the rocky, well-drained benchland of Dry Creek Valley. The gravelly loam and warm Sonoma afternoons turned out to be perfect — the vines took hold and never looked back.',
      'Today their grandchildren tend the same rows, now more than fifty years old. Ancient roots find moisture deep in the hillside, concentrating flavor in ways no irrigation system can replicate. We produce fewer than 400 cases a year and wouldn\'t have it any other way.',
    ],
    signoff: '— The Marchetti Family',
  },

  highlights: [
    '50-year-old estate vines',
    'Dry-farmed benchland',
    'Fewer than 400 cases annually',
  ],

  wines: [
    {
      name: 'Old Vine Zinfandel',
      varietal: 'Zinfandel',
      type: 'Red' as const,
      image: 'wine-old-vine-zinfandel.jpg',
      notes: 'Intense and layered, with ripe blackberry, black pepper, and a hint of vanilla from neutral oak.',
    },
    {
      name: 'Petite Sirah',
      varietal: 'Petite Sirah',
      type: 'Red' as const,
      image: 'wine-petite-sirah.jpg',
      notes: 'Inky and powerful, with dark plum, blueberry, and a firm tannic structure built for aging.',
    },
    {
      name: 'Cabernet Sauvignon',
      varietal: 'Cabernet Sauvignon',
      type: 'Red' as const,
      image: 'wine-cabernet-sauvignon.jpg',
      notes: 'Structured and elegant, with cassis, cedar, and a long, mineral-driven finish.',
    },
    {
      name: 'Benchland Red Blend',
      varietal: 'Red Wine Blend',
      type: 'Blend' as const,
      image: 'wine-benchland-red-blend.jpg',
      notes: 'Our signature blend of Zinfandel and Petite Sirah — rich, food-friendly, and unmistakably Dry Creek.',
    },
    {
      name: 'Grenache Blanc',
      varietal: 'Grenache Blanc',
      type: 'White' as const,
      image: 'wine-grenache-blanc.jpg',
      notes: 'Bright and aromatic, with Meyer lemon, white peach, and a clean mineral finish.',
    },
  ] satisfies Wine[],

  tastingRoom: {
    available: true,
    note: 'We offer seated tastings in our restored 1920s barn. Reservations appreciated — walk-ins welcome when space allows.',
    hours: [
      { day: 'Thu – Mon', hours: '10:30 AM – 4:30 PM' },
      { day: 'Tue – Wed', hours: 'Closed' },
    ] as BusinessHours[],
    reservationRequired: false,
    reservationLink: 'https://drycreekestate.com/reserve',
  },

  awards: [
    'Gold Medal — San Francisco Chronicle Wine Competition 2024',
    'Best of Class Zinfandel — California State Fair 2023',
    '90 pts — Wine Enthusiast, Old Vine Zinfandel 2022',
  ],

  /** Brand colors injected as CSS custom properties in BaseLayout. */
  theme: {
    brand: '#7b2d42',
    brandDark: '#561f2e',
  },
};

export type SiteConfig = typeof config;
